# please keep this alphabetized
version: 2

linters:
  enable:
    - asciicheck
    - contextcheck
    - forcetypeassert
    - gocritic
    - godot
    - misspell
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

run:
  tests: true
  timeout: 1m

linters-settings:
  goimports:
    local-prefixes: "sigs.k8s.io/dra-example-driver"
